### ISSUE TITLE
Question on LearningActivity-BDA.Rmd

### ISSUE THREAD

**Issue by Sahrear** [tz33cu/ColumbiaX-Statistical-Thinking-for-Data-Science#13]
Hi, I'm new to Baysian model and trying to understand this learning activity.

Under "simulate renewal behaviour and prepare the data":

@tz33cu, Can you please give some idea on How did you derive the values for the beta below?

beta0 <- 0.6 beta1 <- 0.9 beta2 <- 0.6 beta3 <- 0.01 beta4 <- -0.01 beta5 <- -0.2

I'm confused, can you please help?

**Comment by tz33cu** [comment]
They are hypothetical values.
